services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      # Пробрасываем дальше, если в .env заданы
      BOT_TOKEN: ${BOT_TOKEN}
      WEBAPP_URL: ${WEBAPP_URL}
    expose:
      - "8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      WEBAPP_URL: ${WEBAPP_URL}
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      # если будет домен и HTTPS — раскомментируй:
      # - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./backend/static:/srv/static:ro
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
