# Удали строку version: ... (она устарела)

services:
  backend:
    build:
      context: .                 # <— корень проекта
      dockerfile: backend/Dockerfile
    container_name: rumus-backend
    restart: unless-stopped
    networks: [net]

  bot:
    build:
      context: .                 # <— корень проекта
      dockerfile: bot/Dockerfile
    container_name: rumus-bot
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      WEBAPP_URL: https://${DOMAIN}
    depends_on: [backend]
    networks: [net]

  caddy:
    image: caddy:2
    container_name: rumus-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on: [backend]
    networks: [net]

networks:
  net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
